### ISSUE TITLE
use "pip install guidedlda" and got “Command "python setup.py egg_info" failed with error code in ......”

### ISSUE THREAD

**Issue by tszxyuan** [vi3k6i5/GuidedLDA#8] opened 2017-11-14 09:19 UTC
Hello, 
My Anaconda's Version  is 5.0.1 and I use Windows 7.
When I input
pip install guidedlda,
I get an error,
Command "python setup.py egg_info" failed with error code in ......
I'm new to python and I don't know how to solve it .
Hope for your help.

**Comment by vi3k6i5** [comment] 2017-11-15 13:37
Duplicate of https://github.com/vi3k6i5/GuidedLDA/issues/2

@tszxyuan I don't have a windows machine with me. I am unable to replicate this issue :(

**Closed by vi3k6i5** 2017-11-15 13:37 UTC
Labels: duplicate

**Comment by tszxyuan** [comment] 2017-11-17 02:32
Ok, thank you all the same.
